#ifndef CONFIG_H
#define CONFIG_H

#define SERIAL_BAUD 115200
#define WIFI_SSID "YOUR_SSID"
#define WIFI_PASSWORD "YOUR_PASSWORD"
#define LIGHTHOUSE_ADDRESS "192.168.1.10"
#define LIGHTHOUSE_PORT 8080
#define LIGHTHOUSE_PATH "/ws"
#define LIGHTHOUSE_RECONNECT_INTERVAL 5000
#define LIGHTHOUSE_PING_INTERVAL 10000
#define LIGHTHOUSE_PONG_INTERVAL 10000
#define LIGHTHOUSE_DISCONNECT_TIMEOUT_COUNT 2

#endif
